version: '3'
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.middleware.conf:/etc/nginx/conf.d/node.template
    env_file: ./.env
    ports:
      - $NGINX_PORT:$NGINX_PORT
    environment:
      - NGINX_PORT=$NGINX_PORT
      - PORT=$PORT
      - WORKER_PORT=$WORKER_PORT
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
  
  conun.middleware.com:
    container_name: conun.middleware.com
    build: .
    restart: unless-stopped
    command: npm run start
    env_file: ./.env
    volumes:
      - .:/conun-middleware-testnet-v3/
      - /conun-middleware-testnet-v3/node_modules
      - ./wallet:/conun-middleware-testnet-v3/wallet
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
      - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
      - ADMIN_WALLET=$ADMIN_WALLET
      - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
      - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DISCOVERY_OPTION=$DISCOVERY_OPTION

      - MONGODB_URL=$MONGODB_URL
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    logging:
      options:
        max-size: 1m
    stdin_open: true
    tty: true

  conun.middleware.worker.com:
      container_name: conun.middleware.worker.com
      build: .
      restart: unless-stopped
      command: npm run worker-start
      env_file: ./.env
      volumes:
        - ./service:/conun-worker-testnet-v3/service
        - ./app.worker.js:/conun-worker-testnet-v3/app.worker.js
        - ./package.json:/conun-worker-testnet-v3/package.json
        - ./common:/conun-worker-testnet-v3/common
        - ./app/web3:/conun-worker-testnet-v3/app/web3
        - ./app/invoke:/conun-worker-testnet-v3/app/invoke
        - ./models:/conun-worker-testnet-v3/models
        - ./middleware/auth:/conun-worker-testnet-v3/middleware/auth
        - ./node_modules:/conun-worker-testnet-v3/node_modules
        - ./wallet:/conun-worker-testnet-v3/wallet
      
      ports:
        - $WORKER_PORT:$WORKER_PORT
      environment:
        - PORT=$WORKER_PORT
        - NODE_ENV=$NODE_ENV
        - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
        - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
        - ADMIN_WALLET=$ADMIN_WALLET
        - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
        - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
        - ETHER_WS_PROVIDER=$ETHER_WS_PROVIDER
        - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
        - DISCOVERY_OPTION=$DISCOVERY_OPTION

        - MONGODB_URL=$MONGODB_URL
        - MONGODB_USER=$MONGODB_USER
        - MONGODB_PASSWORD=$MONGODB_PASSWORD
        - MONGODB_NAME=$MONGODB_NAME
        - MONGODB_PORT=$MONGODB_PORT
      logging:
        options:
          max-size: 1m
      stdin_open: true
      tty: true