version: '2.2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.middleware.conf:/etc/nginx/conf.d/default.conf:ro
    env_file: ./.env
    ports:
      - $NGINX_PORT:$NGINX_PORT
    environment:
      - NGINX_PORT=$NGINX_PORT
      - API_HOST=$API_HOST
      - PORT_1=$PORT_1
      - PORT_2=$PORT_2
      - PORT_3=$PORT_3
      - WORKER_PORT_1=$WORKER_PORT_1
      - WORKER_PORT_2=$WORKER_PORT_2
      - WORKER_PORT_3=$WORKER_PORT_3
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db:/data/db
      - ./mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_NAME
    logging:
      options:
        max-size: 1m
  conun.middleware.1.com:
    container_name: conun.middleware.1.com
    build: .
    restart: unless-stopped
    command: npm run start
    env_file: ./.env
    volumes:
      - .:/conun-middleware-testnet-v3/
      - /conun-middleware-testnet-v3/node_modules
      - ./wallet:/conun-middleware-testnet-v3/wallet
    ports:
      - $PORT_1:$PORT_1
    environment:
      - PORT=$PORT_1
      - NODE_ENV=$NODE_ENV
      - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
      - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
      - ADMIN_WALLET=$ADMIN_WALLET
      - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
      - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DISCOVERY_OPTION=$DISCOVERY_OPTION
      - MONGODB_URL=mongodb
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - mongodb
    logging:
      options:
        max-size: 1m
    stdin_open: true
    tty: true
  conun.middleware.2.com:
    container_name: conun.middleware.2.com
    build: .
    restart: unless-stopped
    command: npm run start
    env_file: ./.env
    volumes:
      - .:/conun-middleware-testnet-v3/
      - /conun-middleware-testnet-v3/node_modules
      - ./wallet:/conun-middleware-testnet-v3/wallet
    ports:
      - $PORT_2:$PORT_2
    environment:
      - PORT=$PORT_2
      - NODE_ENV=$NODE_ENV
      - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
      - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
      - ADMIN_WALLET=$ADMIN_WALLET
      - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
      - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DISCOVERY_OPTION=$DISCOVERY_OPTION
      - MONGODB_URL=mongodb
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - mongodb
    logging:
      options:
        max-size: 1m
    stdin_open: true
    tty: true
  conun.middleware.3.com:
    container_name: conun.middleware.3.com
    build: .
    restart: unless-stopped
    command: npm run start
    env_file: ./.env
    volumes:
      - .:/conun-middleware-testnet-v3/
      - /conun-middleware-testnet-v3/node_modules
      - ./wallet:/conun-middleware-testnet-v3/wallet
    ports:
      - $PORT_3:$PORT_3
    environment:
      - PORT=$PORT_3
      - NODE_ENV=$NODE_ENV
      - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
      - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
      - ADMIN_WALLET=$ADMIN_WALLET
      - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
      - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DISCOVERY_OPTION=$DISCOVERY_OPTION
      - MONGODB_URL=mongodb
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - mongodb
    logging:
      options:
        max-size: 1m
    stdin_open: true
    tty: true
  conun.middleware.worker.1.com:
    container_name: conun.middleware.worker.1.com
    build: .
    restart: unless-stopped
    command: npm run worker
    env_file: ./.env
    volumes:
      - ./service:/conun-worker-testnet-v3/service
      - ./package.json:/conun-worker-testnet-v3/package.json
      - ./common:/conun-worker-testnet-v3/common
      - ./app/web3:/conun-worker-testnet-v3/app/web3
      - ./app/invoke:/conun-worker-testnet-v3/app/invoke
      - ./models:/conun-worker-testnet-v3/models
      - ./middleware/auth:/conun-worker-testnet-v3/middleware/auth
      - ./node_modules:/conun-worker-testnet-v3/node_modules
      - ./wallet:/conun-worker-testnet-v3/wallet
    ports:
      - $WORKER_PORT_1:$WORKER_PORT_1
    environment:
      - WORKER_PORT=$WORKER_PORT_1
      - NODE_ENV=$NODE_ENV
      - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
      - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
      - ADMIN_WALLET=$ADMIN_WALLET
      - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
      - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
      - ETHER_WS_PROVIDER=$ETHER_WS_PROVIDER
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DISCOVERY_OPTION=$DISCOVERY_OPTION
      - MONGODB_URL=mongodb
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - mongodb
    logging:
      options:
        max-size: 1m
    stdin_open: true
    tty: true
  conun.middleware.worker.2.com:
    container_name: conun.middleware.worker.2.com
    build: .
    restart: unless-stopped
    command: npm run worker
    env_file: ./.env
    volumes:
      - ./service:/conun-worker-testnet-v3/service
      - ./package.json:/conun-worker-testnet-v3/package.json
      - ./common:/conun-worker-testnet-v3/common
      - ./app/web3:/conun-worker-testnet-v3/app/web3
      - ./app/invoke:/conun-worker-testnet-v3/app/invoke
      - ./models:/conun-worker-testnet-v3/models
      - ./middleware/auth:/conun-worker-testnet-v3/middleware/auth
      - ./node_modules:/conun-worker-testnet-v3/node_modules
      - ./wallet:/conun-worker-testnet-v3/wallet
    ports:
      - $WORKER_PORT_2:$WORKER_PORT_2
    environment:
      - WORKER_PORT=$WORKER_PORT_2
      - NODE_ENV=$NODE_ENV
      - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
      - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
      - ADMIN_WALLET=$ADMIN_WALLET
      - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
      - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
      - ETHER_WS_PROVIDER=$ETHER_WS_PROVIDER
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DISCOVERY_OPTION=$DISCOVERY_OPTION
      - MONGODB_URL=mongodb
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - mongodb
    logging:
      options:
        max-size: 1m
    stdin_open: true
    tty: true
  conun.middleware.worker.3.com:
    container_name: conun.middleware.worker.3.com
    build: .
    restart: unless-stopped
    command: npm run worker
    env_file: ./.env
    volumes:
      - ./service:/conun-worker-testnet-v3/service
      - ./package.json:/conun-worker-testnet-v3/package.json
      - ./common:/conun-worker-testnet-v3/common
      - ./app/web3:/conun-worker-testnet-v3/app/web3
      - ./app/invoke:/conun-worker-testnet-v3/app/invoke
      - ./models:/conun-worker-testnet-v3/models
      - ./middleware/auth:/conun-worker-testnet-v3/middleware/auth
      - ./node_modules:/conun-worker-testnet-v3/node_modules
      - ./wallet:/conun-worker-testnet-v3/wallet
    ports:
      - $WORKER_PORT_3:$WORKER_PORT_3
    environment:
      - WORKER_PORT=$WORKER_PORT_3
      - NODE_ENV=$NODE_ENV
      - ETHER_CON_CONTRACT_ADDRESS=$ETHER_CON_CONTRACT_ADDRESS
      - ETHER_BRIDGE_CONTRACT_ADDRESS=$ETHER_BRIDGE_CONTRACT_ADDRESS
      - ADMIN_WALLET=$ADMIN_WALLET
      - ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
      - ETHER_HTTP_PROVIDER=$ETHER_HTTP_PROVIDER
      - ETHER_WS_PROVIDER=$ETHER_WS_PROVIDER
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DISCOVERY_OPTION=$DISCOVERY_OPTION
      - MONGODB_URL=mongodb
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - mongodb
    logging:
      options:
        max-size: 1m
    stdin_open: true
    tty: true
volumes:
  db: